site_id: RN+SI0001
supervisors:
  - ip: 127.0.0.1
    port: 13111

components:
  main:
    TC:
      cycle_time: 6
  signal_group:
    A1:
      plan: '11NBBB'
    A2:
      plan: '1NBBBB'
    B1:
      plan: 'BBB11N'
    B2:
      plan: 'BBB1NB'
  detector_logic:
    DL1:
watchdog_interval: 0.1
watchdog_timeout: 0.2
acknowledgement_timeout: 0.2
reconnect_interval: 0.1

security_codes:
  1: '1111'
  2: '2222'

log:
  active: true
  color: true
  timestamp: true
  id: true
  component: true
  ip: false
  site_id: true
  level: false
  text: true
  direction: true
  json: true
  acknowledgements: false
  watchdogs: false

