port: 14111
guest:
  sxl: tlc
  intervals:
    timer: 0.1
    watchdog: 0.1
  timeouts:
    watchdog: 0.5
    acknowledgement: 0.5
log:
  prefix: '[SUPERVISOR]'
  id: true
  port: true
  json: true
  acknowledgements: false
  watchdogs: false

